name: languagetool_textfield
description: The LanguageTool TextField package is a spell-checker designed for Flutter apps. This is useful for apps that need text input like messaging, notes, and email.
version: 0.0.5
homepage: https://github.com/solid-software/languagetool_textfield/
publish_to: none

environment:
  sdk: '>=2.18.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  async: ^2.11.0
  collection: ^1.18.0
  flutter:
    sdk: flutter
  http: ^1.2.1
  throttling: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  solid_lints: ^0.1.5

flutter:
  uses-material-design: true
  assets:
    - images/
